FROM node:20 as vite-build

WORKDIR /app

COPY package*.json ./

RUN npm install -g npm@10.8.1

RUN npm install


COPY . .

RUN npm run build

FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/configfile.template

RUN rm -rf /usr/share/nginx/html/*

COPY --from=vite-build /app/dist /usr/share/nginx/html
ENV PORT 3000

EXPOSE 3000

CMD sh -c "envsubst '\$PORT' < /etc/nginx/conf.d/configfile.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"